[package]
name = "bottle"
version = "0.1.0"
authors = ["Nicolas Chan <nicolas@nicolaschan.com>"]

[dependencies]
websocket = "0.20.2"
tokio = "0.1.5"
chrono = "0.4.9"

[dependencies.pancurses]
version = "0.16"
features = ["wide"]
